// @auto-generated by SilentSpec | 2026-03-21
// Source: extension.ts

// <SS-IMPORTS-START>
import { activate, deactivate } from '../extension';
import * as vscode from 'vscode';
import * as path from 'path';
import {
  registerSaveHandler,
  outputChannel,
} from './saveHandler';
import { AIProvider } from './ai/aiProvider';
import { OpenAIProvider } from './ai/openaiProvider';
import { ClaudeProvider } from './ai/claudeProvider';
import { OllamaProvider } from './ai/ollamaProvider';
import { GitHubModelsProvider } from './ai/githubModelsProvider';
import { validateResponse } from './utils/validateResponse';
import { processingQueue } from './utils/processingQueue';
import { writeSpecFile, mergeSpecFile, resolveSpecPath } from './fileWriter';
import { runGapFinder } from './gapFinder';
import { TelemetryService } from './telemetry';
jest.mock('path');
jest.mock('vscode');
jest.mock('./saveHandler');
jest.mock('./ai/aiProvider');
jest.mock('./ai/openaiProvider');
jest.mock('./ai/claudeProvider');
jest.mock('./ai/ollamaProvider');
jest.mock('./ai/githubModelsProvider');
jest.mock('./utils/validateResponse');
jest.mock('./utils/processingQueue');
jest.mock('./fileWriter');
jest.mock('./gapFinder');
jest.mock('./telemetry');
// <SS-IMPORTS-END>

// <SS-USER-TESTS>
import * as assert from 'assert';

// You can import and use all API from the 'vscode' module
// as well as import your extension to test it
import * as vscode from 'vscode';
// import * as myExtension from '../../extension';

suite('Extension Test Suite', () => {
	vscode.window.showInformationMessage('Start all tests.');

	test('Sample test', () => {
		assert.strictEqual(-1, [1, 2, 3].indexOf(5));
		assert.strictEqual(-1, [1, 2, 3].indexOf(0));
	});
});
// </SS-USER-TESTS>

// <SS-GENERATED-START>
describe('activate', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should register the correct commands and set up the save handler', () => {
    const mockContext = {
      subscriptions: [],
      workspaceState: {
        get: jest.fn(),
        update: jest.fn(),
      },
      globalState: {
        get: jest.fn().mockReturnValue(false),
        update: jest.fn(),
      },
    } as unknown as vscode.ExtensionContext;

    const registerCommandMock = jest.spyOn(vscode.commands, 'registerCommand').mockImplementation(() => ({ dispose: jest.fn() }));
    const statusBarItemMock = {
      show: jest.fn(),
      text: '',
      tooltip: '',
      backgroundColor: undefined,
      command: '',
    } as unknown as vscode.StatusBarItem;
    jest.spyOn(vscode.window, 'createStatusBarItem').mockReturnValue(statusBarItemMock);
    const saveHandlerMock = jest.spyOn(registerSaveHandler, 'mockImplementation').mockImplementation();

    // Call activate function
    activate(mockContext);

    expect(vscode.window.createStatusBarItem).toHaveBeenCalledWith(vscode.StatusBarAlignment.Right, 100);
    expect(statusBarItemMock.show).toHaveBeenCalled();
    expect(registerCommandMock).toHaveBeenCalledTimes(5); // "togglePause", "setApiKey", "openLog", "showStats", "generateNow"

    expect(registerCommandMock).toHaveBeenCalledWith(
      'silentspec.togglePause',
      expect.any(Function)
    );
    expect(registerCommandMock).toHaveBeenCalledWith(
      'silentspec.setApiKey',
      expect.any(Function)
    );
    expect(registerCommandMock).toHaveBeenCalledWith(
      'silentspec.openLog',
      expect.any(Function)
    );
    expect(registerCommandMock).toHaveBeenCalledWith(
      'silentspec.showStats',
      expect.any(Function)
    );
    expect(registerCommandMock).toHaveBeenCalledWith(
      'silentspec.generateNow',
      expect.any(Function)
    );
    expect(saveHandlerMock).toHaveBeenCalled();
    expect(mockContext.subscriptions).toHaveLength(6);
  });
});

describe('deactivate', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should abort all active controllers and clear the set', async () => {
    const mockAbort = jest.fn();
    const mockController = { abort: mockAbort };
    const mockSet = new Set([mockController]);

    // Mock the activeControllers variable
    (activeControllers as any as jest.Mocked<Set<unknown>>) = mockSet;

    // Call deactivate
    deactivate();

    expect(mockAbort).toHaveBeenCalled();
    expect(activeControllers.size).toBe(0);
  });
});
// <SS-GENERATED-END>