import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { resolveSpecPath, resolveSpecPathWithInfo, writeSpecFile } from '../fileWriter';

describe('resolveSpecPath', () => {
  let root: string;

  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'silent-spec-file-writer-'));
  });

  afterEach(() => {
    fs.rmSync(root, { recursive: true, force: true });
  });

  it('falls back to a beside-source .spec.ts file when no test convention exists', async () => {
    const sourcePath = path.join(root, 'example.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');

    await expect(resolveSpecPath(sourcePath)).resolves.toBe(
      path.join(root, 'example.spec.ts')
    );
  });

  it('uses an adjacent established __tests__ directory convention', async () => {
    const testDir = path.join(root, '__tests__');
    fs.mkdirSync(testDir);
    fs.writeFileSync(path.join(testDir, 'existing.test.ts'), 'describe("x", () => {});');

    const sourcePath = path.join(root, 'example.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');

    await expect(resolveSpecPath(sourcePath)).resolves.toBe(
      path.join(testDir, 'example.test.ts')
    );
  });

  it('reuses an existing beside-source spec file before creating a new path', async () => {
    const sourcePath = path.join(root, 'example.ts');
    const specPath = path.join(root, 'example.test.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');
    fs.writeFileSync(specPath, '// @auto-generated by SilentSpec\n// <SS-GENERATED-START v="1" covered="example">\ndescribe("example", () => {});\n// <SS-GENERATED-END>');

    await expect(resolveSpecPath(sourcePath)).resolves.toBe(specPath);
  });

  it('creates a sister path beside an unmanaged source-directory spec', async () => {
    const sourcePath = path.join(root, 'example.ts');
    const unmanagedPath = path.join(root, 'example.spec.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');
    fs.writeFileSync(unmanagedPath, 'describe("hand written", () => {});');

    await expect(resolveSpecPathWithInfo(sourcePath)).resolves.toMatchObject({
      specPath: path.join(root, 'example.silentspec.spec.ts'),
      companionPath: unmanagedPath,
      reason: 'new-sister-for-unmanaged',
    });
  });

  it('prefers .test.ts only when the test convention count is higher', async () => {
    fs.writeFileSync(path.join(root, 'a.test.ts'), '');
    fs.writeFileSync(path.join(root, 'b.test.ts'), '');
    fs.writeFileSync(path.join(root, 'c.spec.ts'), '');
    const sourcePath = path.join(root, 'example.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');

    await expect(resolveSpecPath(sourcePath)).resolves.toBe(
      path.join(root, 'example.test.ts')
    );
  });

  it('prefers .spec.ts when test and spec convention counts are tied', async () => {
    fs.writeFileSync(path.join(root, 'a.test.ts'), '');
    fs.writeFileSync(path.join(root, 'b.spec.ts'), '');
    const sourcePath = path.join(root, 'example.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');

    await expect(resolveSpecPath(sourcePath)).resolves.toBe(
      path.join(root, 'example.spec.ts')
    );
  });

  it('finds an existing managed spec in an ancestor test directory', async () => {
    const srcDir = path.join(root, 'src', 'utils');
    const ancestorTests = path.join(root, 'src', '__tests__');
    fs.mkdirSync(srcDir, { recursive: true });
    fs.mkdirSync(ancestorTests, { recursive: true });
    const sourcePath = path.join(srcDir, 'example.ts');
    const specPath = path.join(ancestorTests, 'example.spec.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');
    fs.writeFileSync(specPath, '// @auto-generated by SilentSpec\n// <SS-GENERATED-START v="1" covered="example">\ndescribe("example", () => {});\n// <SS-GENERATED-END>');

    await expect(resolveSpecPathWithInfo(sourcePath)).resolves.toMatchObject({
      specPath,
      reason: 'existing-managed-ancestor',
    });
  });

  it('does not treat bare test.ts beside source as a naming convention signal', async () => {
    fs.writeFileSync(path.join(root, 'test.ts'), 'export const value = 1;');
    const sourcePath = path.join(root, 'example.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');

    await expect(resolveSpecPath(sourcePath)).resolves.toBe(
      path.join(root, 'example.spec.ts')
    );
  });

  it('treats bare test.ts inside a test directory as a naming convention signal', async () => {
    const testDir = path.join(root, '__tests__');
    fs.mkdirSync(testDir);
    fs.writeFileSync(path.join(testDir, 'test.ts'), 'describe("x", () => {});');
    const sourcePath = path.join(root, 'example.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');

    await expect(resolveSpecPath(sourcePath)).resolves.toBe(
      path.join(testDir, 'example.test.ts')
    );
  });

  it('creates a sister path beside an unmanaged spec in a test directory', async () => {
    const testDir = path.join(root, '__tests__');
    fs.mkdirSync(testDir);
    const sourcePath = path.join(root, 'example.ts');
    const unmanagedPath = path.join(testDir, 'example.spec.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');
    fs.writeFileSync(unmanagedPath, 'describe("hand written", () => {});');

    await expect(resolveSpecPathWithInfo(sourcePath)).resolves.toMatchObject({
      specPath: path.join(testDir, 'example.silentspec.spec.ts'),
      companionPath: unmanagedPath,
      reason: 'new-sister-for-unmanaged',
    });
  });

  it('reuses an existing managed sister file', async () => {
    const sourcePath = path.join(root, 'example.ts');
    const unmanagedPath = path.join(root, 'example.spec.ts');
    const sisterPath = path.join(root, 'example.silentspec.spec.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');
    fs.writeFileSync(unmanagedPath, 'describe("hand written", () => {});');
    fs.writeFileSync(sisterPath, '// @auto-generated by SilentSpec\n// <SS-GENERATED-START v="1" covered="example">\ndescribe("example", () => {});\n// <SS-GENERATED-END>');

    await expect(resolveSpecPathWithInfo(sourcePath)).resolves.toMatchObject({
      specPath: sisterPath,
      reason: 'existing-managed-sister',
    });
  });

  it('writes a companion header when creating a sister file', async () => {
    const sourcePath = path.join(root, 'example.ts');
    const unmanagedPath = path.join(root, 'example.spec.ts');
    fs.writeFileSync(sourcePath, 'export function example() { return true; }');
    fs.writeFileSync(unmanagedPath, 'describe("hand written", () => {});');
    const aiOutput = [
      '// <SS-GENERATED-START>',
      'describe("example", () => {',
      '  it("works", () => {',
      '    expect(example()).toBe(true);',
      '  });',
      '});',
      '// <SS-GENERATED-END>',
    ].join('\n');

    await writeSpecFile(
      sourcePath,
      aiOutput,
      () => undefined,
      { version: 1, covered: ['example'], pending: [] },
      ['example']
    );

    const sisterPath = path.join(root, 'example.silentspec.spec.ts');
    expect(fs.readFileSync(sisterPath, 'utf8')).toContain(
      '// Companion to: example.spec.ts (hand-written - never modified by SilentSpec)'
    );
  });
});
