// @auto-generated by SilentSpec | 2026-04-05
// Source: src/fileWriter.ts
// Functions covered: resolveSpecPath, writeSpecFile, appendGapTests, updateMarker

// <SS-IMPORTS-START>
import { resolveSpecPath, writeSpecFile, appendGapTests, updateMarker } from '../fileWriter';
import * as path from 'path';
import * as fs from 'fs';
import { readMarker, buildMarkerLine, splitAIOutput, updateMarkerOnly } from '../utils/markerManager';
import { isUnmanagedContent } from '../utils/unmanagedSpec';
import {
  stripEchoedLinesFromBlock,
  stripEchoedUserTestsSection,
  validateAssembledMarkerCounts,
} from '../utils/stripEchoedContent';
jest.mock('path');
jest.mock('fs');
jest.mock('../utils/markerManager');
jest.mock('../utils/unmanagedSpec');
jest.mock('../utils/stripEchoedContent');
// <SS-IMPORTS-END>

// <SS-HELPERS-START>

// <SS-HELPERS-END>

// <SS-USER-TESTS>
// Add your own tests here — SilentSpec will never modify this section
// </SS-USER-TESTS>

// <SS-GENERATED-START v="1" covered="resolveSpecPath,writeSpecFile,appendGapTests,updateMarker">
// ─── resolveSpecPath ───────────────────────────────────────────────────────────

describe('resolveSpecPath', () => {
  it('should return the computed spec path for a given source path', async () => {
    const sourcePath = '/user/project/src/example.ts';
    (path.join as jest.Mock).mockReturnValue('/user/project/__tests__/example.spec.ts');
    const result = await resolveSpecPath(sourcePath);
    expect(result).toBe('/user/project/__tests__/example.spec.ts');
  });

  it('should handle an optional log function', async () => {
    const sourcePath = '/user/project/src/example.ts';
    const log = jest.fn();
    await resolveSpecPath(sourcePath, log);
    expect(log).not.toHaveBeenCalled(); // Example case, adjust based on actual log calls
  });

  it('should handle non-existent path gracefully', async () => {
    const sourcePath = '/non/existent/path.ts';
    (path.join as jest.Mock).mockImplementation(() => { throw new Error('Path error'); });
    await expect(resolveSpecPath(sourcePath)).rejects.toThrow('Path error');
  });
});

// ─── writeSpecFile ────────────────────────────────────────────────────────────

describe('writeSpecFile', () => {
  beforeEach(() => jest.clearAllMocks());

  it('should successfully write a spec file and return true', async () => {
    const sourcePath = '/user/project/src/example.ts';
    const aiOutput = 'test output';
    const marker = { version: 1, covered: [], pending: [] } as SSMarker;
    const log = jest.fn();

    (fs.promises.writeFile as jest.Mock).mockResolvedValue(undefined);
    
    const result = await writeSpecFile(sourcePath, aiOutput, log, marker);

    expect(result).toBe(true);
    expect(fs.promises.writeFile).toHaveBeenCalledWith(expect.any(String), expect.stringContaining(aiOutput));
  });

  it('should return false if an error occurs during file writing', async () => {
    const sourcePath = '/user/project/src/example.ts';
    const aiOutput = 'test output';
    const marker = { version: 1, covered: [], pending: [] } as SSMarker;
    const log = jest.fn();

    (fs.promises.writeFile as jest.Mock).mockRejectedValue(new Error('Write error'));

    const result = await writeSpecFile(sourcePath, aiOutput, log, marker);

    expect(result).toBe(false);
  });
});

// ─── appendGapTests ───────────────────────────────────────────────────────────

describe('appendGapTests', () => {
  beforeEach(() => jest.clearAllMocks());

  it('should append gap tests to the existing file', async () => {
    const sourcePath = '/user/project/src/example.ts';
    const newTests = 'new test cases';
    const updatedMarker = { version: 1, covered: [], pending: [] } as SSMarker;
    const log = jest.fn();

    (fs.promises.readFile as jest.Mock).mockResolvedValue('existing content');
    (fs.promises.writeFile as jest.Mock).mockResolvedValue(undefined);

    await appendGapTests(sourcePath, newTests, updatedMarker, log);

    expect(fs.promises.writeFile).toHaveBeenCalledTimes(1);
    expect(fs.promises.writeFile).toHaveBeenCalledWith(expect.any(String), expect.stringContaining(newTests));
  });

  it('should log a warning if the file cannot be read', async () => {
    const sourcePath = '/user/project/src/example.ts';
    const newTests = 'new test cases';
    const updatedMarker = { version: 1, covered: [], pending: [] } as SSMarker;
    const log = jest.fn();

    (fs.promises.readFile as jest.Mock).mockRejectedValue(new Error('Read error'));

    await expect(appendGapTests(sourcePath, newTests, updatedMarker, log)).rejects.toThrow('Read error');
  });
});

// ─── updateMarker ─────────────────────────────────────────────────────────────

describe('updateMarker', () => {
  beforeEach(() => jest.clearAllMocks());

  it('updates the marker in the file and logs the action', async () => {
    const sourcePath = '/user/project/src/example.ts';
    const updatedMarker = { version: 2, covered: ['newFn'], pending: [] } as SSMarker;
    const log = jest.fn();

    (fs.promises.readFile as jest.Mock).mockResolvedValue('content with marker');
    (fs.promises.writeFile as jest.Mock).mockResolvedValue(undefined);

    await updateMarker(sourcePath, updatedMarker, log);

    expect(log).toHaveBeenCalledWith(expect.stringContaining('Updated marker'));
  });

  it('should throw an error if the marker cannot be updated', async () => {
    const sourcePath = '/user/project/src/example.ts';
    const updatedMarker = { version: 2, covered: ['newFn'], pending: [] } as SSMarker;
    const log = jest.fn();

    (fs.promises.readFile as jest.Mock).mockRejectedValue(new Error('Read error'));

    await expect(updateMarker(sourcePath, updatedMarker, log)).rejects.toThrow('Read error');
  });
});
// <SS-GENERATED-END>
