import { isUnmanagedContent } from '../utils/unmanagedSpec';

// ── Managed — SilentSpec header ───────────────────────────────────────────────

test('content with @auto-generated header is managed', () => {
  const content = [
    '// @auto-generated by SilentSpec | 2024-01-01',
    '// Source: src/myModule.ts',
    '',
    'describe("suite", () => {});',
  ].join('\n');
  expect(isUnmanagedContent(content)).toBe(false);
});

// ── Managed — SS zone markers ─────────────────────────────────────────────────

test('content with SS-IMPORTS-START marker is managed', () => {
  expect(isUnmanagedContent('// <SS-IMPORTS-START>\n// <SS-IMPORTS-END>\n')).toBe(false);
});

test('content with SS-IMPORTS-END marker is managed', () => {
  expect(isUnmanagedContent('// <SS-IMPORTS-END>\n')).toBe(false);
});

test('content with SS-HELPERS-START marker is managed', () => {
  expect(isUnmanagedContent('// <SS-HELPERS-START>\n// <SS-HELPERS-END>\n')).toBe(false);
});

test('content with SS-USER-TESTS marker is managed', () => {
  expect(isUnmanagedContent('// <SS-USER-TESTS>\n// </SS-USER-TESTS>\n')).toBe(false);
});

test('content with SS-GENERATED-START prefix marker is managed', () => {
  // SS_START_PREFIX is used as a prefix; any line starting with it is a marker
  expect(isUnmanagedContent('// <SS-GENERATED-START | covered: [fn1]>\n// <SS-GENERATED-END>\n')).toBe(false);
});

test('content with SS-GENERATED-END marker is managed', () => {
  expect(isUnmanagedContent('// <SS-GENERATED-END>\n')).toBe(false);
});

// ── Unmanaged ─────────────────────────────────────────────────────────────────

test('hand-written test file with no SilentSpec indicators is unmanaged', () => {
  const content = [
    "import { add } from '../src/math';",
    '',
    "describe('add', () => {",
    "  it('adds two numbers', () => {",
    '    expect(add(1, 2)).toBe(3);',
    '  });',
    '});',
  ].join('\n');
  expect(isUnmanagedContent(content)).toBe(true);
});

test('empty string is unmanaged', () => {
  // Empty files have no indicators — treated as unmanaged.
  // isUnmanagedSpec() guards against this by returning false for non-existent
  // files; a readable empty file that somehow exists is correctly flagged unmanaged.
  expect(isUnmanagedContent('')).toBe(true);
});

test('file with only regular comments is unmanaged', () => {
  const content = '// This is a test file\n// Written by hand\n';
  expect(isUnmanagedContent(content)).toBe(true);
});

test('partial keyword that does not match any marker is unmanaged', () => {
  // "SS-IMPORTS" without the enclosing comment syntax must NOT trigger managed
  const content = 'const SS_IMPORTS = true;\n';
  expect(isUnmanagedContent(content)).toBe(true);
});

// ── Header substring must match exactly ──────────────────────────────────────

test('content with "auto-generated" but not the exact SilentSpec header is unmanaged', () => {
  const content = '// auto-generated by some other tool\n';
  expect(isUnmanagedContent(content)).toBe(true);
});
