import {
  stripEchoedLinesFromBlock,
  stripEchoedUserTestsSection,
  validateAssembledMarkerCounts,
} from '../utils/stripEchoedContent';

// ── Helpers ───────────────────────────────────────────────────────────────────

function makeValidSpec(importsContent = '', helpersContent = '', userContent = '', generatedContent = ''): string {
  return [
    '// @auto-generated by SilentSpec | 2024-01-01',
    '// Source: src/math.ts',
    '// Functions covered: add',
    '',
    '// <SS-IMPORTS-START>',
    importsContent,
    '// <SS-IMPORTS-END>',
    '',
    '// <SS-HELPERS-START>',
    helpersContent,
    '// <SS-HELPERS-END>',
    '',
    '// <SS-USER-TESTS>',
    userContent,
    '// </SS-USER-TESTS>',
    '',
    '// <SS-GENERATED-START v="1" covered="add">',
    generatedContent,
    '// <SS-GENERATED-END>',
  ].join('\n');
}

// ── Layer 1: stripEchoedLinesFromBlock ────────────────────────────────────────

test('strips all six zone-marker lines from a helpers block', () => {
  const input = [
    '// <SS-IMPORTS-START>',
    'import { foo } from "./foo"',
    '// <SS-IMPORTS-END>',
    '// <SS-HELPERS-START>',
    'const helper = () => {};',
    '// <SS-HELPERS-END>',
    '// <SS-USER-TESTS>',
    '// </SS-USER-TESTS>',
  ].join('\n');
  const result = stripEchoedLinesFromBlock(input);
  expect(result).not.toContain('// <SS-IMPORTS-START>');
  expect(result).not.toContain('// <SS-IMPORTS-END>');
  expect(result).not.toContain('// <SS-HELPERS-START>');
  expect(result).not.toContain('// <SS-HELPERS-END>');
  expect(result).not.toContain('// <SS-USER-TESTS>');
  expect(result).not.toContain('// </SS-USER-TESTS>');
  expect(result).toContain('import { foo } from "./foo"');
  expect(result).toContain('const helper = () => {};');
});

test('strips echoed @auto-generated header line', () => {
  const input = '// @auto-generated by SilentSpec | 2024-01-01\nimport { add } from "../math"';
  const result = stripEchoedLinesFromBlock(input);
  expect(result).not.toContain('// @auto-generated by SilentSpec');
  expect(result).toContain('import { add } from "../math"');
});

test('strips echoed // Source: and // Functions covered: header lines', () => {
  const input = [
    '// Source: src/math.ts',
    '// Functions covered: add, subtract',
    'import { add } from "../math"',
  ].join('\n');
  const result = stripEchoedLinesFromBlock(input);
  expect(result).not.toContain('// Source:');
  expect(result).not.toContain('// Functions covered:');
  expect(result).toContain('import { add } from "../math"');
});

test('preserves legitimate import and helper lines unchanged', () => {
  const input = [
    'import { add, subtract } from "../math"',
    'jest.mock("../db")',
    'const makeUser = (id: number) => ({ id, name: "test" });',
  ].join('\n');
  expect(stripEchoedLinesFromBlock(input)).toBe(input);
});

test('empty input returns empty output', () => {
  expect(stripEchoedLinesFromBlock('')).toBe('');
});

test('input with no markers or header lines is returned unchanged', () => {
  const input = 'import { fn } from "./fn";\nconst x = 1;';
  expect(stripEchoedLinesFromBlock(input)).toBe(input);
});

test('strips only exact zone-marker lines — lines that merely mention markers are preserved', () => {
  // A comment that is NOT the exact zone-marker line should be kept
  const notAMarker = '// regular comment about imports';
  const input = `// <SS-IMPORTS-START>\n${notAMarker}\nimport { x } from "./x"`;
  const result = stripEchoedLinesFromBlock(input);
  // The exact zone-marker line is gone
  expect(result.split('\n').some(l => l.trim() === '// <SS-IMPORTS-START>')).toBe(false);
  // The non-marker comment and import survive
  expect(result).toContain(notAMarker);
  expect(result).toContain('import { x } from "./x"');
});

// ── Layer 2: stripEchoedUserTestsSection ──────────────────────────────────────

test('strips an echoed SS-USER-TESTS block from testsBlock, preserving surrounding generated content', () => {
  const testsBlock = [
    '// <SS-GENERATED-START v="1" covered="add">',
    '// <SS-USER-TESTS>',
    "describe('userFn', () => { it('user test', () => {}); });",
    '// </SS-USER-TESTS>',
    "describe('add', () => { it('works', () => {}); });",
    '// <SS-GENERATED-END>',
  ].join('\n');
  const result = stripEchoedUserTestsSection(testsBlock);
  expect(result).not.toContain('// <SS-USER-TESTS>');
  expect(result).not.toContain('// </SS-USER-TESTS>');
  expect(result).not.toContain("describe('userFn'");
  expect(result).toContain("describe('add'");
  expect(result).toContain('// <SS-GENERATED-START');
  expect(result).toContain('// <SS-GENERATED-END>');
});

test('strips multiple echoed SS-USER-TESTS blocks', () => {
  const testsBlock = [
    '// <SS-GENERATED-START v="1" covered="add">',
    '// <SS-USER-TESTS>',
    "describe('user1', () => {});",
    '// </SS-USER-TESTS>',
    "describe('add', () => {});",
    '// <SS-USER-TESTS>',
    "describe('user2', () => {});",
    '// </SS-USER-TESTS>',
    '// <SS-GENERATED-END>',
  ].join('\n');
  const result = stripEchoedUserTestsSection(testsBlock);
  expect(result).not.toContain("describe('user1'");
  expect(result).not.toContain("describe('user2'");
  expect(result).toContain("describe('add'");
});

test('testsBlock with no SS-USER-TESTS is returned unchanged', () => {
  const testsBlock = [
    '// <SS-GENERATED-START v="1" covered="add">',
    "describe('add', () => { it('works', () => {}); });",
    '// <SS-GENERATED-END>',
  ].join('\n');
  expect(stripEchoedUserTestsSection(testsBlock)).toBe(testsBlock);
});

// ── Layer 3: validateAssembledMarkerCounts ────────────────────────────────────

test('returns null for a valid spec with all 8 markers appearing exactly once', () => {
  const spec = makeValidSpec(
    'import { add } from "../math"',
    '',
    '',
    "describe('add', () => { it('works', () => {}); });"
  );
  expect(validateAssembledMarkerCounts(spec)).toBeNull();
});

test('returns error for duplicate SS-IMPORTS-START', () => {
  const spec = makeValidSpec() + '\n// <SS-IMPORTS-START>';
  const result = validateAssembledMarkerCounts(spec);
  expect(result).not.toBeNull();
  expect(result).toContain('SS-IMPORTS-START');
  expect(result).toContain('duplicate');
});

test('returns error for duplicate SS-HELPERS-START', () => {
  const spec = makeValidSpec() + '\n// <SS-HELPERS-START>';
  const result = validateAssembledMarkerCounts(spec);
  expect(result).not.toBeNull();
  expect(result).toContain('SS-HELPERS-START');
});

test('returns error for duplicate SS-GENERATED-START', () => {
  const spec = makeValidSpec() + '\n// <SS-GENERATED-START v="1" covered="">';
  const result = validateAssembledMarkerCounts(spec);
  expect(result).not.toBeNull();
  expect(result).toContain('SS-GENERATED-START');
});

test('returns error string identifying the specific missing marker', () => {
  // Remove SS-HELPERS-START to simulate a missing marker
  const spec = makeValidSpec().replace('// <SS-HELPERS-START>\n', '');
  const result = validateAssembledMarkerCounts(spec);
  expect(result).not.toBeNull();
  expect(result).toContain('SS-HELPERS-START');
  expect(result).toContain('missing');
});

test('returns null for minimal valid spec (all 8 markers, minimal content)', () => {
  const minimal = [
    '// <SS-IMPORTS-START>',
    '// <SS-IMPORTS-END>',
    '// <SS-HELPERS-START>',
    '// <SS-HELPERS-END>',
    '// <SS-USER-TESTS>',
    '// </SS-USER-TESTS>',
    '// <SS-GENERATED-START v="1" covered="">',
    '// <SS-GENERATED-END>',
  ].join('\n');
  expect(validateAssembledMarkerCounts(minimal)).toBeNull();
});
