// ── Strip echoed LLM content ──────────────────────────────────────────────────
//
// Pure helpers with no vscode dependency. Used by writeSpecFile to sanitise
// the three blocks returned by splitAIOutput before they are assembled into
// the spec file.
//
// The LLM is asked to wrap its output in // <SS-GENERATED-START> /
// // <SS-GENERATED-END> only. However, if it has seen the full 4-zone file
// structure (e.g. via the Existing Test Style sample), it may echo back:
//   - Zone-marker comment lines (// <SS-IMPORTS-START>, etc.)
//   - The @auto-generated / Source: / Functions covered: header lines
//   - A complete // <SS-USER-TESTS> ... // </SS-USER-TESTS> block
//
// Layers:
//   1. stripEchoedLinesFromBlock  — imports/helpers blocks
//   2. stripEchoedUserTestsSection — testsBlock
//   3. validateAssembledMarkerCounts — assembled spec content pre-write

// Zone-marker lines that must never appear inside imports or helpers blocks.
const ZONE_MARKER_LINES = new Set([
  '// <SS-IMPORTS-START>',
  '// <SS-IMPORTS-END>',
  '// <SS-HELPERS-START>',
  '// <SS-HELPERS-END>',
  '// <SS-USER-TESTS>',
  '// </SS-USER-TESTS>',
]);

// Header prefixes the LLM might echo if it has seen the file header.
const HEADER_ECHO_PREFIXES = [
  '// @auto-generated by SilentSpec',
  '// Source:',
  '// Functions covered:',
];

/**
 * Layer 1 — Remove echoed zone-marker lines and header-echo lines from a
 * block string (importsBlock or helpersBlock). All other lines are preserved.
 */
export function stripEchoedLinesFromBlock(block: string): string {
  return block
    .split('\n')
    .filter(line => {
      const t = line.trim();
      if (ZONE_MARKER_LINES.has(t)) { return false; }
      if (HEADER_ECHO_PREFIXES.some(prefix => t.startsWith(prefix))) { return false; }
      return true;
    })
    .join('\n');
}

/**
 * Layer 2 — Remove any echoed SS-USER-TESTS section from the testsBlock
 * string. All occurrences are removed using a non-greedy match so unrelated
 * generated content outside the user-tests block is preserved.
 */
export function stripEchoedUserTestsSection(testsBlock: string): string {
  return testsBlock.replace(/\/\/ <SS-USER-TESTS>[\s\S]*?\/\/ <\/SS-USER-TESTS>\n?/g, '');
}

// Markers validated in the fully assembled spec content.
// For SS-GENERATED-START the value is a prefix (markers carry version attributes).
const ASSEMBLY_MARKERS: Array<[string, string]> = [
  ['// <SS-IMPORTS-START>',  'SS-IMPORTS-START'],
  ['// <SS-IMPORTS-END>',    'SS-IMPORTS-END'],
  ['// <SS-HELPERS-START>',  'SS-HELPERS-START'],
  ['// <SS-HELPERS-END>',    'SS-HELPERS-END'],
  ['// <SS-USER-TESTS>',     'SS-USER-TESTS'],
  ['// </SS-USER-TESTS>',    '/SS-USER-TESTS'],
  ['// <SS-GENERATED-START', 'SS-GENERATED-START'],
  ['// <SS-GENERATED-END>',  'SS-GENERATED-END'],
];

/**
 * Layer 3 — Validate that every zone marker appears exactly once in the
 * fully assembled spec content. Returns null if valid; returns a
 * human-readable message describing the first violation found.
 *
 * Catches both duplicate markers (LLM echo slipped through Layers 1/2) and
 * missing markers (internal assembly bug).
 */
export function validateAssembledMarkerCounts(content: string): string | null {
  for (const [marker, name] of ASSEMBLY_MARKERS) {
    const count = content.split(marker).length - 1;
    if (count === 0) { return `missing ${name}`; }
    if (count > 1)  { return `duplicate ${name} (${count} occurrences)`; }
  }
  return null;
}
