import * as fs from 'fs';
import { SS_START_PREFIX, SS_END } from './markerManager';

// Private constants that mirror fileWriter.ts zone markers — kept here so
// this module has no vscode dependency and can be unit-tested with plain strings.
const SS_IMPORTS_START = '// <SS-IMPORTS-START>';
const SS_IMPORTS_END   = '// <SS-IMPORTS-END>';
const SS_HELPERS_START = '// <SS-HELPERS-START>';
const SS_HELPERS_END   = '// <SS-HELPERS-END>';
const SS_USER_START    = '// <SS-USER-TESTS>';
const SS_USER_END      = '// </SS-USER-TESTS>';

/**
 * Returns true if the given spec-file content has neither a SilentSpec header
 * nor any SS zone marker — indicating this is a hand-written test file that
 * SilentSpec must never overwrite.
 *
 * Exported so callers can check content they have already read without a
 * second file I/O, and so it can be tested with plain strings.
 */
export function isUnmanagedContent(content: string): boolean {
  const hasSilentSpecHeader = content.includes('// @auto-generated by SilentSpec');
  const hasAnySSMarker =
    content.includes(SS_IMPORTS_START) || content.includes(SS_IMPORTS_END) ||
    content.includes(SS_HELPERS_START) || content.includes(SS_HELPERS_END) ||
    content.includes(SS_USER_START)    || content.includes(SS_USER_END) ||
    content.includes(SS_START_PREFIX)  || content.includes(SS_END);
  return !hasSilentSpecHeader && !hasAnySSMarker;
}

/**
 * Returns true if the file at filePath exists AND its content is unmanaged
 * (has neither a SilentSpec header nor any SS zone marker).
 *
 * Returns false for a non-existent or unreadable file so that the normal
 * generation/write flow can proceed and writeSpecFile() remains the final guard.
 */
export async function isUnmanagedSpec(filePath: string): Promise<boolean> {
  if (!fs.existsSync(filePath)) { return false; }
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    return isUnmanagedContent(content);
  } catch {
    return false; // unreadable → not unmanaged; let writeSpecFile be the final guard
  }
}
