import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

// Phase 9 — dynamic header with date, source file, and functions covered
function buildHeader(sourcePath?: string, exportedFunctions?: string[]): string {
  const date = new Date().toISOString().split('T')[0];
  const sourceNote = sourcePath
    ? `\n// Source: ${path.basename(sourcePath)}`
    : '';
  const fnNote = exportedFunctions && exportedFunctions.length > 0
    ? `\n// Functions covered: ${exportedFunctions.join(', ')}`
    : '';
  return `// @auto-generated by SilentSpec | ${date}${sourceNote}${fnNote}`;
}

// Block markers
const SS_IMPORTS_START  = '// <SS-IMPORTS-START>';
const SS_IMPORTS_END    = '// <SS-IMPORTS-END>';
const SS_START          = '// <SS-GENERATED-START>';
const SS_END            = '// <SS-GENERATED-END>';
const SS_USER_START     = '// <SS-USER-TESTS>';
const SS_USER_CONTENT   = '// Add your own tests below — SilentSpec will never modify this section';
const SS_USER_END       = '// </SS-USER-TESTS>';

// Convention detection
async function detectNamingConvention(dir: string): Promise<'.spec.ts' | '.test.ts'> {
  // Step 1 — check __tests__ or tests subfolder of current dir first
  const testDirs = ['__tests__', 'tests', 'test'];
  for (const testDir of testDirs) {
    const testDirPath = path.join(dir, testDir);
    if (fs.existsSync(testDirPath) && fs.lstatSync(testDirPath).isDirectory()) {
      try {
        const files = fs.readdirSync(testDirPath);
        if (files.some(f => /\.(test)\.[tj]sx?$/.test(f))) { return '.test.ts'; }
        if (files.some(f => /\.(spec)\.[tj]sx?$/.test(f))) { return '.spec.ts'; }
      } catch { /* skip */ }
    }
  }

  // Step 2 — check the same directory as the source file
  try {
    const files = fs.readdirSync(dir);
    if (files.some(f => /\.(test)\.[tj]sx?$/.test(f))) { return '.test.ts'; }
    if (files.some(f => /\.(spec)\.[tj]sx?$/.test(f))) { return '.spec.ts'; }
  } catch { /* fall through */ }

  // Step 3 — check parent directories up to workspace root
  const workspaceFolders = vscode.workspace.workspaceFolders;
  const workspaceRoot = workspaceFolders?.[0]?.uri.fsPath;
  let current = path.dirname(dir);
  while (current !== dir && workspaceRoot && current.startsWith(workspaceRoot)) {
    try {
      const files = fs.readdirSync(current);
      if (files.some(f => /\.(test)\.[tj]sx?$/.test(f))) { return '.test.ts'; }
      if (files.some(f => /\.(spec)\.[tj]sx?$/.test(f))) { return '.spec.ts'; }
    } catch { /* skip */ }
    dir = current;
    current = path.dirname(current);
  }

  // Step 4 — workspace-wide scan as last resort
  const testFiles = await vscode.workspace.findFiles(
    '**/*.test.{ts,tsx,js,jsx}', '**/node_modules/**', 1
  );
  const specFiles = await vscode.workspace.findFiles(
    '**/*.spec.{ts,tsx,js,jsx}', '**/node_modules/**', 1
  );

  if (testFiles.length > 0) { return '.test.ts'; }
  if (specFiles.length > 0) { return '.spec.ts'; }

  return '.spec.ts';
}

export async function resolveSpecPath(sourcePath: string): Promise<string> {
  const ext  = path.extname(sourcePath);
  const base = path.basename(sourcePath, ext);
  const dir  = path.dirname(sourcePath);

  const convention = await detectNamingConvention(dir);

  const specExt = ext === '.tsx' ? (convention === '.test.ts' ? '.test.tsx' : '.spec.tsx')
                : ext === '.jsx' ? (convention === '.test.ts' ? '.test.jsx' : '.spec.jsx')
                : convention;

  const specName = `${base}${specExt}`;
  const testDirs = ['__tests__', 'tests', 'test'];

  // Check if existing spec/test file already exists — if so, use it
  const allExts = ['.spec.ts', '.test.ts', '.spec.tsx', '.test.tsx', '.spec.jsx', '.test.jsx'];
  for (const testDir of testDirs) {
    const potentialPath = path.join(dir, testDir);
    if (fs.existsSync(potentialPath) && fs.lstatSync(potentialPath).isDirectory()) {
      for (const e of allExts) {
        const existingPath = path.join(potentialPath, `${base}${e}`);
        if (fs.existsSync(existingPath)) {
          return existingPath;
        }
      }
      return path.join(potentialPath, specName);
    }
  }

  // Check same directory for existing file
  for (const e of allExts) {
    const existingPath = path.join(dir, `${base}${e}`);
    if (fs.existsSync(existingPath)) {
      return existingPath;
    }
  }

  // Use getWorkspaceFolder for correct multi-root workspace support
  const workspaceFolder = vscode.workspace.getWorkspaceFolder(
    vscode.Uri.file(sourcePath)
  );
  const workspaceRoot = workspaceFolder?.uri.fsPath;

  if (workspaceRoot && workspaceRoot !== dir) {
    for (const testDir of testDirs) {
      const rootTestPath = path.join(workspaceRoot, testDir);
      if (fs.existsSync(rootTestPath) &&
          fs.lstatSync(rootTestPath).isDirectory()) {
        const relativePath = path.relative(workspaceRoot, dir);
        const mirroredPath = path.join(rootTestPath, relativePath);
        return path.join(mirroredPath, specName);
      }
    }
  }

  return path.join(dir, specName);
}

// ─── Content extraction helpers ───────────────────────────────────────────────

/**
 * Extract the imports block from AI output (everything before the first describe/test/it)
 * Falls back to all import/jest.mock lines if no clear boundary found.
 */
function extractImportsBlock(inner: string): string {
  const lines = inner.split('\n');
  const importLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (
      trimmed.startsWith('import ') ||
      trimmed.startsWith('jest.mock(') ||
      trimmed.startsWith('vi.mock(') ||
      trimmed.startsWith('jest.unmock(') ||
      trimmed === '' && importLines.length > 0 && importLines[importLines.length - 1].trim() === ''
    ) {
      importLines.push(line);
    } else if (
      trimmed.startsWith('describe(') ||
      trimmed.startsWith('test(') ||
      trimmed.startsWith('it(') ||
      trimmed.startsWith('beforeEach(') ||
      trimmed.startsWith('beforeAll(') ||
      trimmed.startsWith('afterEach(') ||
      trimmed.startsWith('afterAll(')
    ) {
      break;
    } else if (trimmed !== '') {
      // Non-import, non-empty line before describe — still part of setup
      importLines.push(line);
    }
  }

  return importLines.join('\n').trim();
}

/**
 * Extract the test body (everything after imports/mocks)
 */
function extractTestBody(inner: string): string {
  const lines = inner.split('\n');
  let foundBody = false;
  const bodyLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!foundBody) {
      if (
        trimmed.startsWith('describe(') ||
        trimmed.startsWith('test(') ||
        trimmed.startsWith('it(') ||
        trimmed.startsWith('beforeEach(') ||
        trimmed.startsWith('beforeAll(') ||
        trimmed.startsWith('afterEach(') ||
        trimmed.startsWith('afterAll(')
      ) {
        foundBody = true;
        bodyLines.push(line);
      }
    } else {
      bodyLines.push(line);
    }
  }

  // If no describe/test found, return full inner (fallback)
  if (!foundBody) { return inner.trim(); }

  return bodyLines.join('\n').trim();
}

/**
 * Extract SS-GENERATED inner content from AI response
 */
function extractInner(validated: string): string {
  if (!validated.includes(SS_START)) { return validated.trim(); }
  return validated.split(SS_START)[1]?.split(SS_END)[0]?.trim() ?? '';
}

/**
 * Extract existing SS-IMPORTS block content
 */
function extractExistingImports(existing: string): string {
  if (!existing.includes(SS_IMPORTS_START)) { return ''; }
  return existing.split(SS_IMPORTS_START)[1]?.split(SS_IMPORTS_END)[0]?.trim() ?? '';
}

/**
 * Extract existing SS-USER-TESTS block content
 */
function extractExistingUserTests(existing: string): string {
  if (!existing.includes(SS_USER_START)) { return ''; }
  return existing.split(SS_USER_START)[1]?.split(SS_USER_END)[0]?.trim() ?? '';
}

/**
 * Extract any content that exists outside all SS blocks (legacy user content)
 * This handles files that had content before SilentSpec was introduced
 */
function extractLegacyContent(existing: string): string {
  // Remove header
  let content = existing.replace(/^\/\/ @auto-generated by SilentSpec.*\n(\/\/ Source:.*\n)?(\/\/ Functions covered:.*\n)?/, '');
  
  // Remove SS-IMPORTS block
  content = content.replace(/\/\/ <SS-IMPORTS-START>[\s\S]*?\/\/ <SS-IMPORTS-END>\n?/, '');
  
  // Remove SS-GENERATED block
  content = content.replace(/\/\/ <SS-GENERATED-START>[\s\S]*?\/\/ <SS-GENERATED-END>\n?/, '');
  
  // Remove SS-USER-TESTS block
  content = content.replace(/\/\/ <SS-USER-TESTS>[\s\S]*?\/\/ <\/SS-USER-TESTS>\n?/, '');
  
  return content.trim();
}

// ─── File content builders ─────────────────────────────────────────────────────

/**
 * Build content for a brand new spec file
 * Structure: header → SS-IMPORTS → SS-USER-TESTS (empty) → SS-GENERATED
 */
function buildNewFileContent(
  validated: string,
  sourcePath?: string,
  exportedFunctions?: string[]
): string {
  const inner = extractInner(validated);
  const importsBlock = extractImportsBlock(inner);
  const testBody = extractTestBody(inner);

  return [
    buildHeader(sourcePath, exportedFunctions),
    '',
    SS_IMPORTS_START,
    importsBlock,
    SS_IMPORTS_END,
    '',
    SS_USER_START,
    SS_USER_CONTENT,
    SS_USER_END,
    '',
    SS_START,
    testBody,
    SS_END,
  ].join('\n');
}

/**
 * Build content for an existing spec file
 * Structure: header → SS-IMPORTS (updated) → SS-USER-TESTS (preserved) → SS-GENERATED (updated)
 */
function buildUpdatedFileContent(
  existing: string,
  validated: string,
  log: (msg: string) => void,
  sourcePath?: string,
  exportedFunctions?: string[]
): string {
  const inner = extractInner(validated);

  if (!inner) {
    log('Warning: extracted inner content is empty — preserving existing spec file unchanged');
    return existing;
  }

  const newImportsBlock = extractImportsBlock(inner);
  const newTestBody = extractTestBody(inner);

  // Preserve existing user tests
  const existingUserTests = extractExistingUserTests(existing);
  
  // Check for any legacy content outside SS blocks (e.g. existing tests before SilentSpec)
  const legacyContent = extractLegacyContent(existing);

  // Build user tests zone — preserve existing + migrate legacy content
  let userZoneContent: string;
  if (existingUserTests) {
    userZoneContent = existingUserTests;
  } else if (legacyContent) {
    // Migrate legacy content into user zone
    log('Notice: migrating existing tests into SS-USER-TESTS zone');
    userZoneContent = legacyContent;
  } else {
    userZoneContent = SS_USER_CONTENT;
  }

  return [
    buildHeader(sourcePath, exportedFunctions),
    '',
    SS_IMPORTS_START,
    newImportsBlock,
    SS_IMPORTS_END,
    '',
    SS_USER_START,
    userZoneContent,
    SS_USER_END,
    '',
    SS_START,
    newTestBody,
    SS_END,
  ].join('\n');
}

// ─── Internal writer ──────────────────────────────────────────────────────────

async function writeSpecFileToPath(
  specPath: string,
  validated: string,
  log: (msg: string) => void,
  sourcePath?: string,
  exportedFunctions?: string[]
): Promise<void> {
  const specUri = vscode.Uri.file(specPath);
  const isNew   = !fs.existsSync(specPath);

  // Git conflict marker check
  if (!isNew) {
    try {
      const existingContent = fs.readFileSync(specPath, 'utf8');
      if (existingContent.includes('<<<<<<<')) {
        log('Warning: Git conflict markers detected in spec file — skipping to prevent corruption');
        void vscode.window.showWarningMessage(
          'SilentSpec: Git conflict markers found in spec file. Resolve conflicts before auto-merging.'
        );
        return;
      }
    } catch { /* skip */ }
  }

  const finalContent = isNew
    ? buildNewFileContent(validated, sourcePath, exportedFunctions)
    : buildUpdatedFileContent(
        fs.readFileSync(specPath, 'utf8'),
        validated,
        log,
        sourcePath,
        exportedFunctions
      );

  try {
    const edit = new vscode.WorkspaceEdit();

    if (isNew) {
      fs.mkdirSync(path.dirname(specPath), { recursive: true });

      edit.createFile(specUri, {
        ignoreIfExists: true,
        contents: Buffer.from(finalContent),
      });
      await vscode.workspace.applyEdit(edit);

      const doc = await vscode.workspace.openTextDocument(specUri);
      await doc.save();

      log(`Created: ${path.basename(specPath)} — SS-IMPORTS + SS-GENERATED blocks written, SS-USER-TESTS ready`);

      const shouldOpen = vscode.workspace
        .getConfiguration('silentspec')
        .get<boolean>('openSpecOnCreate', true);

      if (shouldOpen) {
        await vscode.window.showTextDocument(doc, {
          viewColumn: vscode.ViewColumn.Beside,
          preserveFocus: true,
        });
      }

    } else {
      const doc = await vscode.workspace.openTextDocument(specUri);
      const fullRange = new vscode.Range(
        doc.positionAt(0),
        doc.positionAt(doc.getText().length)
      );
      edit.replace(specUri, fullRange, finalContent);
      await vscode.workspace.applyEdit(edit);
      await doc.save();

      log(`Updated: ${path.basename(specPath)} — SS-IMPORTS + SS-GENERATED regenerated, SS-USER-TESTS preserved`);
    }

  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);

    if (msg.includes('EACCES') || msg.includes('permission')) {
      void vscode.window.showErrorMessage(
        'SilentSpec: Cannot write spec file — check folder permissions.'
      );
    }

    log(`Error: file writer failed for ${path.basename(specPath)} — ${msg}`);
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function writeSpecFile(
  sourcePath: string,
  validated: string,
  log: (msg: string) => void,
  exportedFunctions?: string[]
): Promise<void> {
  const specPath = await resolveSpecPath(sourcePath);
  await writeSpecFileToPath(specPath, validated, log, sourcePath, exportedFunctions);
}

// Gap Finder merge writer — appends gap tests to existing SS-GENERATED block
export async function mergeSpecFile(
  sourcePath: string,
  newContent: string,
  log: (msg: string) => void,
  exportedFunctions?: string[]
): Promise<void> {
  const specPath = await resolveSpecPath(sourcePath);

  const strippedNew = newContent
    .replace(/^\/\/ <SS-GENERATED-START>\s*/m, '')
    .replace(/\/\/ <SS-GENERATED-END>\s*$/m, '')
    .trim();

  if (!strippedNew) {
    log('Warning: gap generation returned empty content — spec file unchanged');
    return;
  }

  let existingGenerated = '';

  if (fs.existsSync(specPath)) {
    try {
      const specBytes = await vscode.workspace.fs.readFile(
        vscode.Uri.file(specPath)
      );
      const specContent = Buffer.from(specBytes).toString('utf8');

      if (specContent.includes('<<<<<<<')) {
        log('Warning: Git conflict markers detected — skipping merge');
        void vscode.window.showWarningMessage(
          'SilentSpec: Git conflict markers found in spec file. Resolve conflicts before auto-merging.'
        );
        return;
      }

      const startIdx = specContent.indexOf(SS_START);
      const endIdx   = specContent.indexOf(SS_END);

      if (startIdx !== -1 && endIdx !== -1) {
        existingGenerated = specContent
          .slice(startIdx + SS_START.length, endIdx)
          .trim();
        log('Gap merge: extracted existing SS-GENERATED block');
      }
    } catch {
      log('Gap merge: could not read existing spec — writing fresh');
    }
  }

  const combined = existingGenerated
    ? `${existingGenerated}\n\n${strippedNew}`
    : strippedNew;

  const merged = [
    SS_START,
    combined,
    SS_END,
  ].join('\n');

  await writeSpecFileToPath(specPath, merged, log, sourcePath, exportedFunctions);
  log('Gap merge: spec file updated — gap tests appended to SS-GENERATED block');
}