import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import {
  SSMarker,
  SS_START_PREFIX,
  SS_END,
  readMarker,
  buildMarkerLine,
  splitAIOutput,
  updateMarkerOnly,
} from './utils/markerManager';

// ─── 4-Block Zone Structure ───────────────────────────────────────────────────
//
//   // @auto-generated by SilentSpec | YYYY-MM-DD
//   // Source: foo.ts
//   // Functions covered: fn1, fn2, ...
//
//   // <SS-IMPORTS-START>      ← SYSTEM: all imports, replaced every run
//   // <SS-IMPORTS-END>
//
//   // <SS-HELPERS-START>      ← SYSTEM: helper factories, replaced every run
//   // <SS-HELPERS-END>
//
//   // <SS-USER-TESTS>         ← USER: never touched after creation
//   // </SS-USER-TESTS>
//
//   // <SS-GENERATED-START>    ← SYSTEM: AI test blocks, replaced every run
//   // <SS-GENERATED-END>
//
// System zones are fully replaced each run — single source of truth, no dedup needed.
// User zone is written once and never modified again.

const SS_IMPORTS_START = '// <SS-IMPORTS-START>';
const SS_IMPORTS_END   = '// <SS-IMPORTS-END>';
const SS_HELPERS_START = '// <SS-HELPERS-START>';
const SS_HELPERS_END   = '// <SS-HELPERS-END>';
const SS_USER_START    = '// <SS-USER-TESTS>';
const SS_USER_END      = '// </SS-USER-TESTS>';

const SS_USER_PLACEHOLDER = '// Add your own tests here — SilentSpec will never modify this section';

const TEST_DIRS = ['__tests__', 'tests', 'test', 'specs'];

// ─── Header ───────────────────────────────────────────────────────────────────

function buildHeader(sourcePath?: string, exportedFunctions?: string[]): string {
  const date = new Date().toISOString().split('T')[0];
  const sourceNote = sourcePath ? `\n// Source: ${path.basename(sourcePath)}` : '';
  const fnNote = exportedFunctions && exportedFunctions.length > 0
    ? `\n// Functions covered: ${exportedFunctions.join(', ')}`
    : '';
  return `// @auto-generated by SilentSpec | ${date}${sourceNote}${fnNote}`;
}

// ─── Structure helpers ────────────────────────────────────────────────────────

function hasFullStructure(content: string): boolean {
  return (
    content.includes(SS_IMPORTS_START) &&
    content.includes(SS_IMPORTS_END) &&
    content.includes(SS_HELPERS_START) &&
    content.includes(SS_HELPERS_END) &&
    content.includes(SS_USER_START) &&
    content.includes(SS_USER_END) &&
    content.includes(SS_START_PREFIX) &&
    content.includes(SS_END)
  );
}

function validateSSStructure(content: string): string | null {
  const startIdx = content.indexOf(SS_START_PREFIX);
  const endIdx   = content.indexOf(SS_END);
  if (startIdx === -1 && endIdx === -1) { return null; }
  if (startIdx === -1) { return 'SS-GENERATED-START missing'; }
  if (endIdx === -1)   { return 'SS-GENERATED-END missing'; }
  if (startIdx >= endIdx) { return 'SS-GENERATED-START after SS-GENERATED-END'; }
  if (content.split(SS_START_PREFIX).length - 1 > 1) { return 'duplicate SS-GENERATED-START'; }
  if (content.split(SS_END).length - 1 > 1)          { return 'duplicate SS-GENERATED-END'; }
  return null;
}

// ─── File assembly ────────────────────────────────────────────────────────────

function buildFullFile(
  importsBlock: string,
  helpersBlock: string,
  userTests: string,
  generatedBlock: string,
  sourcePath?: string,
  exportedFunctions?: string[]
): string {
  return [
    buildHeader(sourcePath, exportedFunctions),
    '',
    SS_IMPORTS_START,
    importsBlock,
    SS_IMPORTS_END,
    '',
    SS_HELPERS_START,
    helpersBlock,
    SS_HELPERS_END,
    '',
    SS_USER_START,
    userTests,
    SS_USER_END,
    '',
    generatedBlock,
  ].join('\n').replace(/\n{3,}/g, '\n\n') + '\n';
}

// ─── System zone replacement (Case 2) ────────────────────────────────────────

function replaceSystemZones(
  existing: string,
  importsBlock: string,
  helpersBlock: string,
  log: (msg: string) => void
): string | null {
  // Duplicate markers → abort the entire write, not just the zone update.
  // Returning null signals to the caller to skip the write entirely.
  if (existing.split(SS_IMPORTS_START).length - 1 > 1 ||
      existing.split(SS_IMPORTS_END).length - 1 > 1) {
    log('Warning: duplicate SS-IMPORTS markers detected — aborting write to prevent corruption');
    void vscode.window.showWarningMessage('SilentSpec: Duplicate zone markers found. Delete the spec file and re-save to regenerate.');
    return null;
  }
  if (existing.split(SS_HELPERS_START).length - 1 > 1 ||
      existing.split(SS_HELPERS_END).length - 1 > 1) {
    log('Warning: duplicate SS-HELPERS markers detected — aborting write to prevent corruption');
    void vscode.window.showWarningMessage('SilentSpec: Duplicate zone markers found. Delete the spec file and re-save to regenerate.');
    return null;
  }

  let result = existing;

  const importsStart = result.indexOf(SS_IMPORTS_START);
  const importsEnd   = result.indexOf(SS_IMPORTS_END);
  if (importsStart !== -1 && importsEnd !== -1 && importsStart < importsEnd) {
    result =
      result.slice(0, importsStart) +
      SS_IMPORTS_START + '\n' + importsBlock + '\n' + SS_IMPORTS_END +
      result.slice(importsEnd + SS_IMPORTS_END.length);
  }

  const helpersStart = result.indexOf(SS_HELPERS_START);
  const helpersEnd   = result.indexOf(SS_HELPERS_END);
  if (helpersStart !== -1 && helpersEnd !== -1 && helpersStart < helpersEnd) {
    result =
      result.slice(0, helpersStart) +
      SS_HELPERS_START + '\n' + helpersBlock + '\n' + SS_HELPERS_END +
      result.slice(helpersEnd + SS_HELPERS_END.length);
  }

  return result;
}

// ─── Local model/enum mock filter ─────────────────────────────────────────────
//
// TypeScript erases model/type/enum/constants files at compile time.
// Mocking them removes enum values and silently breaks all assertions.
// These patterns match typical "no-mock" file names used in the wild.

const LOCAL_MODEL_SEGMENT_RE = /^(models?|types?|enums?|constants?|dtos?|entities|entity|interfaces?|schemas?)$/i;
const LOCAL_MODEL_SUFFIX_RE  = /\.(model|type|enum|constant|dto|entity|interface|schema)$/i;

function isLocalModelMockPath(mockPath: string): boolean {
  if (!mockPath.startsWith('.')) { return false; }
  const lastSegment = (mockPath.split('/').pop() ?? '').replace(/\.[tj]sx?$/, '');
  return LOCAL_MODEL_SEGMENT_RE.test(lastSegment) || LOCAL_MODEL_SUFFIX_RE.test(lastSegment);
}

// ─── Import dedup by module path (Case 3 migration only) ─────────────────────
//
// During migration we merge user's existing imports with AI imports.
// Rules:
//   - If a module path (normalized to absolute) already exists in the base set,
//     skip it from additions — the base version is kept as-is.
//   - vi/jest.mock() calls for local model/type/enum/constants files are dropped.
//   - vi/jest.mock() calls for other paths are deduplicated by mock path.
//
// specDir is used to resolve relative paths to absolute for comparison, so
// '../models' and '../../models' that resolve to the same file are treated as equal.
// Secondary basename dedup: two relative imports with the same basename are treated
// as the same module (catches '../models' vs '../../models' across dir boundaries).

function mergeImportBlocks(base: string, additions: string, specDir: string, log?: (msg: string) => void): string {
  const seenPaths     = new Set<string>();
  const seenBasenames = new Set<string>();  // secondary: basename of relative imports
  const seenMockPaths = new Set<string>();
  const resultLines: string[] = [];

  function normalizeModulePath(modulePath: string): string {
    return modulePath.startsWith('.') ? path.resolve(specDir, modulePath) : modulePath;
  }

  function relativeBasename(modulePath: string): string | null {
    if (!modulePath.startsWith('.')) { return null; }
    return path.basename(modulePath).replace(/\.[tj]sx?$/, '');
  }

  // Collect all module paths and mock paths from base imports
  for (const line of base.split('\n')) {
    const fromMatch = line.match(/from\s+['"]([^'"]+)['"]/);
    if (fromMatch) {
      seenPaths.add(normalizeModulePath(fromMatch[1]));
      const bn = relativeBasename(fromMatch[1]);
      if (bn) { seenBasenames.add(bn); }
    }
    const mockMatch = line.trim().match(/^(?:vi|jest)\.mock\s*\(\s*['"]([^'"]+)['"]/);
    if (mockMatch) { seenMockPaths.add(normalizeModulePath(mockMatch[1])); }
    resultLines.push(line);
  }

  if (base.trim()) { resultLines.push(''); } // blank line separator

  // Add only imports/mocks from additions that are new and not filtered
  let inMultiline = false;
  let pendingLines: string[] = [];

  for (const line of additions.split('\n')) {
    const t = line.trim();

    if (inMultiline) {
      pendingLines.push(line);
      const m = line.match(/from\s+['"]([^'"]+)['"]/);
      if (m) {
        inMultiline = false;
        const normalized = normalizeModulePath(m[1]);
        const bn         = relativeBasename(m[1]);
        if (seenPaths.has(normalized) || (bn !== null && seenBasenames.has(bn))) {
          log?.(`Import dedup: '${m[1]}' skipped (already seen as '${normalized}')`);
        } else {
          seenPaths.add(normalized);
          if (bn !== null) { seenBasenames.add(bn); }
          resultLines.push(...pendingLines);
        }
        pendingLines = [];
      }
      continue;
    }

    if (!t.startsWith('import ') && !t.startsWith('vi.mock(') && !t.startsWith('jest.mock(')) {
      if (t) { resultLines.push(line); }
      continue;
    }

    const fromMatch = line.match(/from\s+['"]([^'"]+)['"]/);
    if (fromMatch) {
      // Single-line import — deduplicate by normalized absolute path (primary)
      // and by basename of relative imports (secondary, catches ../x vs ../../x)
      const normalized = normalizeModulePath(fromMatch[1]);
      const bn         = relativeBasename(fromMatch[1]);
      if (seenPaths.has(normalized) || (bn !== null && seenBasenames.has(bn))) {
        log?.(`Import dedup: '${fromMatch[1]}' skipped (already seen as '${normalized}')`);
      } else {
        seenPaths.add(normalized);
        if (bn !== null) { seenBasenames.add(bn); }
        resultLines.push(line);
      }
    } else if (t.startsWith('import ')) {
      // Start of multiline import
      inMultiline  = true;
      pendingLines = [line];
    } else {
      // vi/jest.mock call — filter local model/enum mocks; deduplicate the rest
      const mockPathMatch = t.match(/^(?:vi|jest)\.mock\s*\(\s*['"]([^'"]+)['"]/);
      if (mockPathMatch) {
        const mockPath = mockPathMatch[1];
        if (isLocalModelMockPath(mockPath)) { continue; } // drop — TS erases these at compile time
        const normalized = normalizeModulePath(mockPath);
        if (!seenMockPaths.has(normalized)) {
          seenMockPaths.add(normalized);
          resultLines.push(line);
        }
      } else {
        // Mock without an extractable path (e.g. computed path) — pass through
        resultLines.push(line);
      }
    }
  }

  return resultLines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

// ─── Helper dedup by name (Case 3 migration only) ────────────────────────────
//
// Merge user helpers with AI helpers.
// If user already has a declaration with the same name, skip the AI version.

function mergeHelperBlocks(base: string, additions: string): string {
  const seenNames = new Set<string>();
  const resultLines: string[] = [];

  for (const line of base.split('\n')) {
    const m = line.trim().match(/^(?:export\s+)?(?:const|let|var|function|class)\s+(\w+)/);
    if (m) { seenNames.add(m[1]); }
    resultLines.push(line);
  }

  if (base.trim()) { resultLines.push(''); }

  let skipDepth = 0;
  let skipping  = false;

  for (const line of additions.split('\n')) {
    const t = line.trim();

    if (skipping) {
      for (const ch of line) {
        if (ch === '{') { skipDepth++; }
        if (ch === '}') { skipDepth--; }
      }
      if (skipDepth === 0) { skipping = false; }
      continue;
    }

    const m = t.match(/^(?:export\s+)?(?:const|let|var|function|class)\s+(\w+)/);
    if (m && seenNames.has(m[1])) {
      skipping = true;
      skipDepth = 0;
      for (const ch of line) {
        if (ch === '{') { skipDepth++; }
        if (ch === '}') { skipDepth--; }
      }
      if (skipDepth === 0) { skipping = false; }
      continue;
    }

    if (m) { seenNames.add(m[1]); }
    resultLines.push(line);
  }

  return resultLines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

// ─── Extract existing content from legacy file (Case 3) ───────────────────────

interface LegacyContent { imports: string; helpers: string; tests: string; }

function extractLegacyContent(existing: string): LegacyContent {
  // Strip all SS markers from any previous format
  let content = existing
    .replace(/^\/\/ @auto-generated by SilentSpec.*\n(\/\/ Source:.*\n)?(\/\/ Functions covered:.*\n)?/, '')
    .replace(/\/\/ <SS-USER-IMPORTS-START>[\s\S]*?\/\/ <SS-USER-IMPORTS-END>\n?/g, '')
    .replace(/\/\/ <SS-IMPORTS-START>[\s\S]*?\/\/ <SS-IMPORTS-END>\n?/g, '')
    .replace(/\/\/ <SS-USER-HELPERS-START>[\s\S]*?\/\/ <SS-USER-HELPERS-END>\n?/g, '')
    .replace(/\/\/ <SS-HELPERS-START>[\s\S]*?\/\/ <SS-HELPERS-END>\n?/g, '')
    .replace(/\/\/ <SS-USER-TESTS>[\s\S]*?\/\/ <\/SS-USER-TESTS>\n?/g, '')
    .replace(/\/\/ <SS-GENERATED-START[^\n]*\n[\s\S]*?\/\/ <SS-GENERATED-END>\n?/g, '');

  const lines = content.split('\n');
  const importLines: string[] = [];
  const remainingLines: string[] = [];
  let mockParenDepth   = 0;
  let importBraceDepth = 0;

  // Pass 1: separate imports/mocks from everything else
  for (const line of lines) {
    const t = line.trim();

    if (mockParenDepth > 0) {
      importLines.push(line);
      for (const ch of line) {
        if (ch === '(') { mockParenDepth++; }
        if (ch === ')') { mockParenDepth--; }
      }
      continue;
    }

    if (importBraceDepth > 0) {
      importLines.push(line);
      for (const ch of line) {
        if (ch === '{') { importBraceDepth++; }
        if (ch === '}') { importBraceDepth--; }
      }
      continue;
    }

    if (t.startsWith('import ')) {
      importLines.push(line);
      for (const ch of line) {
        if (ch === '{') { importBraceDepth++; }
        if (ch === '}') { importBraceDepth--; }
      }
      continue;
    }

    if (t.startsWith('vi.mock(') || t.startsWith('jest.mock(')) {
      importLines.push(line);
      for (const ch of line) {
        if (ch === '(') { mockParenDepth++; }
        if (ch === ')') { mockParenDepth--; }
      }
      continue;
    }

    remainingLines.push(line);
  }

  // Pass 2: separate helper declarations from test blocks
  // NOTE: brace depth tracking is heuristic — may miscount for braces inside
  // template literals or strings, but handles the vast majority of real files.
  const helperLines: string[] = [];
  const testLines: string[]   = [];
  let inTestBlock = false;
  let testDepth   = 0;

  for (const line of remainingLines) {
    const t = line.trim();

    if (!inTestBlock) {
      // Regex catches describe/test/it plus variants like describe.only, test.each etc.
      const isTestStart = /^(describe|test|it)[\s.(]/.test(t);

      if (isTestStart) {
        inTestBlock = true;
        testLines.push(line);
        for (const ch of line) {
          if (ch === '{') { testDepth++; }
          if (ch === '}') { testDepth--; }
        }
      } else if (t.length > 0) {
        helperLines.push(line);
      }
    } else {
      testLines.push(line);
      for (const ch of line) {
        if (ch === '{') { testDepth++; }
        if (ch === '}') { testDepth--; }
      }
      if (testDepth === 0) {
        inTestBlock = false;
        testDepth   = 0;
        testLines.push('');
      }
    }
  }

  return {
    imports: importLines.join('\n').trim(),
    helpers: helperLines.join('\n').trim(),
    tests:   testLines.join('\n').trim(),
  };
}

// ─── Spec path resolution ─────────────────────────────────────────────────────

async function detectNamingConvention(dir: string): Promise<'.spec.ts' | '.test.ts'> {
  const testPattern = /\.(test)\.[tj]sx?$/;
  const specPattern = /\.(spec)\.[tj]sx?$/;

  for (const testDir of TEST_DIRS) {
    const testDirPath = path.join(dir, testDir);
    if (fs.existsSync(testDirPath) && fs.lstatSync(testDirPath).isDirectory()) {
      try {
        const files = fs.readdirSync(testDirPath);
        if (files.some(f => testPattern.test(f))) { return '.test.ts'; }
        if (files.some(f => specPattern.test(f))) { return '.spec.ts'; }
      } catch { /* skip */ }
    }
  }

  try {
    const files = fs.readdirSync(dir);
    if (files.some(f => testPattern.test(f))) { return '.test.ts'; }
    if (files.some(f => specPattern.test(f))) { return '.spec.ts'; }
  } catch { /* skip */ }

  const workspaceFolders = vscode.workspace.workspaceFolders;
  const workspaceRoot    = workspaceFolders?.[0]?.uri.fsPath;
  let current = path.dirname(dir);
  while (current !== dir && workspaceRoot && current.startsWith(workspaceRoot)) {
    try {
      const files = fs.readdirSync(current);
      if (files.some(f => testPattern.test(f))) { return '.test.ts'; }
      if (files.some(f => specPattern.test(f))) { return '.spec.ts'; }
    } catch { /* skip */ }
    dir     = current;
    current = path.dirname(current);
  }

  const testFiles = await vscode.workspace.findFiles('**/*.test.{ts,tsx,js,jsx}', '**/node_modules/**', 1);
  const specFiles = await vscode.workspace.findFiles('**/*.spec.{ts,tsx,js,jsx}', '**/node_modules/**', 1);
  if (testFiles.length > 0) { return '.test.ts'; }
  if (specFiles.length > 0) { return '.spec.ts'; }
  return '.spec.ts';
}

export async function resolveSpecPath(sourcePath: string): Promise<string> {
  const ext  = path.extname(sourcePath);
  const base = path.basename(sourcePath, ext);
  const dir  = path.dirname(sourcePath);

  const convention = await detectNamingConvention(dir);

  const preferredExt = (() => {
    if (ext === '.tsx') { return convention === '.test.ts' ? '.test.tsx' : '.spec.tsx'; }
    if (ext === '.jsx') { return convention === '.test.ts' ? '.test.jsx' : '.spec.jsx'; }
    if (ext === '.js')  { return convention === '.test.ts' ? '.test.js'  : '.spec.js';  }
    return convention;
  })();
  const specName = `${base}${preferredExt}`;

  const allVariants = [
    '.spec.ts', '.test.ts', '.spec.tsx', '.test.tsx',
    '.spec.js', '.test.js', '.spec.jsx', '.test.jsx',
  ];
  const primaryExts  = allVariants.filter(e => e.endsWith(ext));
  const fallbackExts = allVariants.filter(e => !e.endsWith(ext));
  const allExts      = [...primaryExts, ...fallbackExts];

  // Pass 1 — existing file in test subfolder adjacent to source
  for (const testDir of TEST_DIRS) {
    const potentialDir = path.join(dir, testDir);
    if (!fs.existsSync(potentialDir) || !fs.lstatSync(potentialDir).isDirectory()) { continue; }
    for (const e of allExts) {
      const candidate = path.join(potentialDir, `${base}${e}`);
      if (fs.existsSync(candidate)) { return candidate; }
    }
  }

  // Pass 2 — existing file in same directory as source
  for (const e of allExts) {
    const candidate = path.join(dir, `${base}${e}`);
    if (fs.existsSync(candidate)) { return candidate; }
  }

  // Pass 3 — walk up to workspace root looking for a test folder
  const workspaceFolderForSearch = vscode.workspace.getWorkspaceFolder(vscode.Uri.file(sourcePath));
  const searchRoot = workspaceFolderForSearch?.uri.fsPath ?? path.parse(dir).root;
  let searchDir = dir;
  while (true) {
    for (const testDir of TEST_DIRS) {
      const potentialDir = path.join(searchDir, testDir);
      if (fs.existsSync(potentialDir) && fs.lstatSync(potentialDir).isDirectory()) {
        return path.join(potentialDir, specName);
      }
    }
    if (searchDir === searchRoot) { break; }
    const parent = path.dirname(searchDir);
    if (parent === searchDir) { break; }
    searchDir = parent;
  }

  // Pass 4 — mirror workspace root test folder structure
  const workspaceFolder = vscode.workspace.getWorkspaceFolder(vscode.Uri.file(sourcePath));
  const workspaceRoot   = workspaceFolder?.uri.fsPath;
  if (workspaceRoot && workspaceRoot !== dir) {
    for (const testDir of TEST_DIRS) {
      const rootTestPath = path.join(workspaceRoot, testDir);
      if (fs.existsSync(rootTestPath) && fs.lstatSync(rootTestPath).isDirectory()) {
        return path.join(rootTestPath, path.relative(workspaceRoot, dir), specName);
      }
    }
  }

  return path.join(dir, specName);
}

// ─── Low-level writer ─────────────────────────────────────────────────────────

async function writeSpecFileToPath(
  specPath: string,
  finalContent: string,
  log: (msg: string) => void,
  targetedRange?: { startIdx: number; endIdx: number; newBlock: string }
): Promise<void> {
  const specUri = vscode.Uri.file(specPath);
  try {
    const edit = new vscode.WorkspaceEdit();
    const doc  = await vscode.workspace.openTextDocument(specUri);

    if (targetedRange) {
      const startPos = doc.positionAt(targetedRange.startIdx);
      const endPos   = doc.positionAt(targetedRange.endIdx);
      edit.replace(specUri, new vscode.Range(startPos, endPos), targetedRange.newBlock);
      await vscode.workspace.applyEdit(edit);
      await doc.save();
      log(`Updated: ${path.basename(specPath)} (targeted splice)`);
    } else {
      const fullRange = new vscode.Range(doc.positionAt(0), doc.positionAt(doc.getText().length));
      edit.replace(specUri, fullRange, finalContent);
      await vscode.workspace.applyEdit(edit);
      await doc.save();
      log(`Updated: ${path.basename(specPath)}`);
    }
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);
    if (msg.includes('EACCES') || msg.includes('permission')) {
      void vscode.window.showErrorMessage('SilentSpec: Cannot write spec file — check folder permissions.');
    }
    log(`Error: file writer failed for ${path.basename(specPath)} — ${msg}`);
  }
}

// ─── Main entry point ─────────────────────────────────────────────────────────
//
// Case 1 — New file: build full 4-block structure from scratch.
//
// Case 2 — Existing file with full structure (steady state):
//   Replace SS-IMPORTS, SS-HELPERS, SS-GENERATED every run.
//   SS-USER-TESTS is never touched.
//
// Case 3 — Existing file without structure (one-time migration):
//   Extract user's imports → merge with AI imports (dedup by module path) → SS-IMPORTS
//   Extract user's helpers → merge with AI helpers (dedup by name) → SS-HELPERS
//   Extract user's test blocks → SS-USER-TESTS (never touched again)
//   AI generated tests → SS-GENERATED

export async function writeSpecFile(
  sourcePath: string,
  aiOutput: string,
  log: (msg: string) => void,
  marker: SSMarker,
  exportedFunctions?: string[],
  mode: 'replace' | 'append' = 'replace'
): Promise<void> {
  const specPath = await resolveSpecPath(sourcePath);
  const { importsBlock, helpersBlock, testsBlock: generatedBlock } = splitAIOutput(aiOutput, marker);

  const markerSummary =
    `covered: [${marker.covered.join(', ')}]` +
    (marker.pending.length > 0 ? ` pending: [${marker.pending.join(', ')}]` : '');

  // ── Case 1: Brand new file ─────────────────────────────────────────────────
  if (!fs.existsSync(specPath)) {
    const specUri = vscode.Uri.file(specPath);
    const edit    = new vscode.WorkspaceEdit();
    const content = buildFullFile(
      importsBlock, helpersBlock, SS_USER_PLACEHOLDER, generatedBlock,
      sourcePath, exportedFunctions
    );
    edit.createFile(specUri, { overwrite: false, ignoreIfExists: false });
    await vscode.workspace.applyEdit(edit);
    await writeSpecFileToPath(specPath, content, log);
    log(`New spec created — ${markerSummary}`);
    return;
  }

  // Read existing file
  let existing: string;
  try {
    existing = fs.readFileSync(specPath, 'utf8');
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);
    log(`Warning: could not read existing spec (${msg}) — skipping`);
    return;
  }

  if (existing.includes('<<<<<<<')) {
    log('Warning: Git conflict markers detected — skipping write');
    void vscode.window.showWarningMessage('SilentSpec: Resolve Git conflicts before regenerating.');
    return;
  }

  // Guard: detect broken SS marker structure before any write or migration
  const hasStart = existing.includes('// <SS-GENERATED-START');
  const hasEnd = existing.includes('// <SS-GENERATED-END>');
  const hasUserBlock = existing.includes('// <SS-USER-TESTS>');

  if (hasStart || hasEnd || hasUserBlock) {
    // File has partial SS structure — validate before proceeding
    const startCount = (existing.match(/\/\/ <SS-GENERATED-START/g) || []).length;
    const endCount = (existing.match(/\/\/ <SS-GENERATED-END>/g) || []).length;
    const startIdx = existing.indexOf('// <SS-GENERATED-START');
    const endIdx = existing.indexOf('// <SS-GENERATED-END>');

    if (startCount > 1) {
      log('Spec file: duplicate SS-GENERATED-START marker');
      return;
    }
    if (hasStart && !hasEnd) {
      log('Spec file: missing SS-GENERATED-END marker');
      return;
    }
    if (!hasStart && hasEnd) {
      log('Spec file: missing SS-GENERATED-END marker');
      return;
    }
    if (hasStart && hasEnd && endIdx < startIdx) {
      log('Spec file: markers out of order');
      return;
    }
  }

  // Guard: SS-GENERATED intact but other zones missing/broken → skip, never migrate
  if (hasStart && hasEnd) {
    const startIdx = existing.indexOf('// <SS-GENERATED-START');
    const endIdx = existing.indexOf('// <SS-GENERATED-END>');
    if (startIdx < endIdx && !hasFullStructure(existing)) {
      log('Spec file: incomplete zone structure — skipping write');
      return;
    }
  }

  // Guard: verify ALL zone markers appear in correct order
  // Required order: SS-IMPORTS-START → SS-IMPORTS-END → SS-HELPERS-START → SS-HELPERS-END
  //                 → SS-USER-TESTS → /SS-USER-TESTS → SS-GENERATED-START → SS-GENERATED-END
  const posImportsStart  = existing.indexOf('// <SS-IMPORTS-START>');
  const posImportsEnd    = existing.indexOf('// <SS-IMPORTS-END>');
  const posHelpersStart  = existing.indexOf('// <SS-HELPERS-START>');
  const posHelpersEnd    = existing.indexOf('// <SS-HELPERS-END>');
  const posUserStart     = existing.indexOf('// <SS-USER-TESTS>');
  const posUserEnd       = existing.indexOf('// </SS-USER-TESTS>');
  const posGenStart      = existing.indexOf('// <SS-GENERATED-START');
  const posGenEnd        = existing.indexOf('// <SS-GENERATED-END>');

  const zoneOrderValid =
    posImportsStart  < posImportsEnd   &&
    posImportsEnd    < posHelpersStart &&
    posHelpersStart  < posHelpersEnd   &&
    posHelpersEnd    < posUserStart    &&
    posUserStart     < posUserEnd      &&
    posUserEnd       < posGenStart     &&
    posGenStart      < posGenEnd;

  if (!zoneOrderValid) {
    log('Spec file: zone order invalid — skipping write');
    return;
  }

  // ── Case 2: Existing file with full 4-block structure ─────────────────────
  if (hasFullStructure(existing)) {
    const validationError = validateSSStructure(existing);
    if (validationError) {
      log(`Warning: SS structure invalid — ${validationError} — skipping write`);
      return;
    }

    // Replace system zones — SS-USER-TESTS is never touched
    // null return means duplicate markers detected — abort entire write
    const withSystemZones = replaceSystemZones(existing, importsBlock, helpersBlock, log);
    if (withSystemZones === null) { return; }

    const { startIdx, endIdx } = readMarker(withSystemZones);
    if (startIdx === -1 || endIdx === -1 || startIdx >= endIdx) {
      log('Warning: readMarker returned invalid range — writing system zones only');
      await writeSpecFileToPath(specPath, withSystemZones, log);
      return;
    }

    const newTestBody = generatedBlock
      .replace(/^\/\/ <SS-GENERATED-START[^\n]*\n/, '')
      .replace(/\n\/\/ <SS-GENERATED-END>$/, '')
      .trim();

    const testBody = (() => {
      if (mode === 'append') {
        const { innerContent: existingGenerated } = readMarker(withSystemZones);
        return existingGenerated.trim()
          ? `${existingGenerated.trim()}\n\n${newTestBody}`
          : newTestBody;
      }
      return newTestBody;
    })();

    const newBlock = [buildMarkerLine(marker), testBody, SS_END].join('\n');

    log(`SS-GENERATED updated — ${markerSummary}`);

    if (withSystemZones !== existing) {
      // System zones changed — full write
      const finalContent =
        withSystemZones.slice(0, startIdx) +
        newBlock +
        withSystemZones.slice(endIdx);
      await writeSpecFileToPath(specPath, finalContent, log);
    } else {
      // Only SS-GENERATED changed — surgical splice
      await writeSpecFileToPath(specPath, withSystemZones, log, { startIdx, endIdx, newBlock });
    }
    return;
  }

  // ── Case 3: One-time migration ─────────────────────────────────────────────
  // Extract user's existing content, merge with AI output, build full structure.
  // After this run the file has full structure — all subsequent saves hit Case 2.
  log('Notice: migrating existing file into SilentSpec zone structure');
  const legacy = extractLegacyContent(existing);

  // Merge imports: user's first (base), AI adds only new module paths
  const mergedImports = mergeImportBlocks(legacy.imports, importsBlock, path.dirname(specPath), log);

  // Merge helpers: user's first (base), AI adds only new named declarations
  const mergedHelpers = mergeHelperBlocks(legacy.helpers, helpersBlock);

  // User's test blocks go into SS-USER-TESTS — never touched again
  const userTests = legacy.tests || SS_USER_PLACEHOLDER;

  const finalContent = buildFullFile(
    mergedImports,
    mergedHelpers,
    userTests,
    generatedBlock,
    sourcePath,
    exportedFunctions
  );

  log(`Migration complete — existing content preserved — ${markerSummary}`);
  await writeSpecFileToPath(specPath, finalContent, log);
}

// ─── Gap batch append ─────────────────────────────────────────────────────────

export async function appendGapTests(
  sourcePath: string,
  newTests: string,
  updatedMarker: SSMarker,
  log: (msg: string) => void
): Promise<void> {
  const specPath = await resolveSpecPath(sourcePath);

  if (!fs.existsSync(specPath)) {
    log('Gap append: spec not found — skipping');
    return;
  }

  let specContent: string;
  try {
    const bytes = await vscode.workspace.fs.readFile(vscode.Uri.file(specPath));
    specContent = Buffer.from(bytes).toString('utf8');
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);
    log(`Gap append: could not read spec file (${msg}) — skipping`);
    return;
  }

  if (specContent.includes('<<<<<<<')) {
    log('Warning: Git conflict markers detected — skipping append');
    void vscode.window.showWarningMessage('SilentSpec: Resolve Git conflicts before regenerating.');
    return;
  }

  if (!specContent.includes(SS_START_PREFIX)) {
    log('Gap append: no SS-GENERATED block found — skipping');
    return;
  }

  const validationError = validateSSStructure(specContent);
  if (validationError) {
    log(`Gap append: SS structure invalid — ${validationError} — skipping`);
    return;
  }

  // Strip imports/helpers from gap output — only test blocks go into SS-GENERATED
  const rawLines = newTests
    .replace(/^\/\/ <SS-GENERATED-START[^\n]*\n/m, '')
    .replace(/\/\/ <SS-GENERATED-END>\s*$/m, '')
    .split('\n');

  const testLines: string[] = [];
  let capturing  = false;
  let braceDepth = 0;

  for (const line of rawLines) {
    const t = line.trim();

    if (!capturing) {
      if (t.startsWith('import ') || t.startsWith('vi.mock(') || t.startsWith('jest.mock(')) {
        continue;
      }
      if (/(describe|it|test)\s*\(/.test(t)) {
        capturing  = true;
        braceDepth = 0;
      }
    }

    if (capturing) {
      testLines.push(line);
      braceDepth += (line.match(/\{/g) ?? []).length;
      braceDepth -= (line.match(/\}/g) ?? []).length;
      if (braceDepth === 0) {
        capturing  = false;
        braceDepth = 0;
        testLines.push('');
      }
    }
  }

  const cleanedTests = testLines.join('\n').trim();
  if (!cleanedTests) {
    log('Gap append: no test content after stripping imports/helpers — skipping');
    return;
  }

  const openBraces  = (cleanedTests.match(/\{/g) ?? []).length;
  const closeBraces = (cleanedTests.match(/\}/g) ?? []).length;
  if (openBraces !== closeBraces) {
    log(`Gap append: unbalanced braces (${openBraces} open, ${closeBraces} close) — skipping`);
    return;
  }

  const { startIdx, endIdx, innerContent } = readMarker(specContent);
  if (startIdx === -1 || endIdx === -1) {
    log('Gap append: readMarker returned invalid positions — skipping');
    return;
  }

  const combined = innerContent.trim()
    ? `${innerContent.trim()}\n\n${cleanedTests}`
    : cleanedTests;

  const newBlock = [buildMarkerLine(updatedMarker), combined, SS_END].join('\n');

  await writeSpecFileToPath(specPath, specContent, log, { startIdx, endIdx, newBlock });

  const markerSummary =
    `covered: [${updatedMarker.covered.join(', ')}]` +
    (updatedMarker.pending.length > 0 ? ` pending: [${updatedMarker.pending.join(', ')}]` : '');
  log(`Gap append complete — ${markerSummary}`);
}

// ─── Marker-only update ───────────────────────────────────────────────────────

export async function updateMarker(
  sourcePath: string,
  updatedMarker: SSMarker,
  log: (msg: string) => void
): Promise<void> {
  const specPath = await resolveSpecPath(sourcePath);
  if (!fs.existsSync(specPath)) { return; }

  try {
    const bytes = await vscode.workspace.fs.readFile(vscode.Uri.file(specPath));
    const content = Buffer.from(bytes).toString('utf8');
    const updated = updateMarkerOnly(content, updatedMarker);
    if (updated !== content) {
      await writeSpecFileToPath(specPath, updated, log);
      log(`Marker updated — covered: ${updatedMarker.covered.length}, pending: ${updatedMarker.pending.length}`);
    }
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);
    log(`Marker update: read failed (${msg}) — skipping`);
  }
}