import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

const SS_HEADER       = '// @auto-generated by SilentSpec';
const SS_START        = '// <SS-GENERATED-START>';
const SS_END          = '// <SS-GENERATED-END>';
const SS_USER_START   = '// <SS-USER-TESTS>';
const SS_USER_CONTENT = '// Add your own tests below — SilentSpec will never modify this section';
const SS_USER_END     = '// </SS-USER-TESTS>';

// Convention detection

async function detectNamingConvention(dir: string): Promise<'.spec.ts' | '.test.ts'> {
  // 1. Same directory — fastest
  try {
    const files = fs.readdirSync(dir);
    if (files.some(f => f.endsWith('.test.ts') || f.endsWith('.test.tsx'))) { return '.test.ts'; }
    if (files.some(f => f.endsWith('.spec.ts') || f.endsWith('.spec.tsx'))) { return '.spec.ts'; }
  } catch { /* fall through */ }

  // 2. Workspace-level scan — covers monorepos, max 1 result for performance
  const testFiles = await vscode.workspace.findFiles('**/*.test.ts', '**/node_modules/**', 1);
  const specFiles = await vscode.workspace.findFiles('**/*.spec.ts', '**/node_modules/**', 1);

  if (testFiles.length > 0) { return '.test.ts'; }
  if (specFiles.length > 0) { return '.spec.ts'; }

  return '.spec.ts'; // default
}

// Spec file placement — exported so extension.ts can pass specPath to promptBuilder

export async function resolveSpecPath(sourcePath: string): Promise<string> {
  const ext  = path.extname(sourcePath);       // .ts | .tsx | .js | .jsx
  const base = path.basename(sourcePath, ext); // PatientCard
  const dir  = path.dirname(sourcePath);

  const convention = await detectNamingConvention(dir); // .spec.ts | .test.ts

  // Mirror source extension — .tsx → .spec.tsx, .jsx → .spec.jsx, .ts/.js → convention
  const specExt = ext === '.tsx' ? '.spec.tsx'
                : ext === '.jsx' ? '.spec.jsx'
                : convention;

  const specName = `${base}${specExt}`;

  const testDirs = ['__tests__', 'tests', 'test'];

  // 1. Check same directory for test folders
  for (const testDir of testDirs) {
    const potentialPath = path.join(dir, testDir);
    if (fs.existsSync(potentialPath) &&
        fs.lstatSync(potentialPath).isDirectory()) {
      return path.join(potentialPath, specName);
    }
  }

  // 2. Check workspace root — monorepo support
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
  if (workspaceRoot && workspaceRoot !== dir) {
    for (const testDir of testDirs) {
      const rootTestPath = path.join(workspaceRoot, testDir);
      if (fs.existsSync(rootTestPath) &&
          fs.lstatSync(rootTestPath).isDirectory()) {
        const relativePath = path.relative(workspaceRoot, dir);
        const mirroredPath = path.join(rootTestPath, relativePath);
        return path.join(mirroredPath, specName);
      }
    }
  }

  // 3. Default — co-located
  return path.join(dir, specName);
}

// Content builders

function extractInner(validated: string): string {
  if (!validated.includes(SS_START)) { return validated.trim(); }
  return validated.split(SS_START)[1]?.split(SS_END)[0]?.trim() ?? '';
}

function buildNewFileContent(validated: string): string {
  const inner = extractInner(validated);
  return [
    SS_HEADER,
    SS_START,
    inner,
    SS_END,
    SS_USER_START,
    SS_USER_CONTENT,
    SS_USER_END,
  ].join('\n');
}

function buildUpdatedFileContent(
  existing: string,
  validated: string,
  log: (msg: string) => void
): string {
  const newInner = extractInner(validated);

  if (!newInner) {
    log('Warning: extracted inner content is empty — preserving existing spec file unchanged');
    return existing;
  }

  const hasMarkers = existing.includes(SS_START) && existing.includes(SS_END);

  let result: string;

  if (!hasMarkers) {
    result = [
      SS_HEADER,
      SS_START,
      newInner,
      SS_END,
      existing.trim(),
    ].join('\n');
  } else {
    const before = existing.split(SS_START)[0].trimEnd();
    const after  = existing.split(SS_END)[1] ?? '';

    result = [
      before.length > 0 ? before + '\n' : '',
      SS_START + '\n',
      newInner + '\n',
      SS_END,
      after,
    ].join('');
  }

  // Ensure SS-USER-TESTS section always exists — re-add if manually deleted
  if (!result.includes(SS_USER_START)) {
    log('Notice: SS-USER-TESTS section missing — restoring');
    result = result.trimEnd() + '\n' + [
      SS_USER_START,
      SS_USER_CONTENT,
      SS_USER_END,
    ].join('\n');
  }

  return result;
}

// Main writer

export async function writeSpecFile(
  sourcePath: string,
  validated: string,
  log: (msg: string) => void
): Promise<void> {
  const specPath = await resolveSpecPath(sourcePath);
  const specUri  = vscode.Uri.file(specPath);
  const isNew    = !fs.existsSync(specPath);

  const finalContent = isNew
    ? buildNewFileContent(validated)
    : buildUpdatedFileContent(fs.readFileSync(specPath, 'utf8'), validated, log);

  try {
    const edit = new vscode.WorkspaceEdit();

    if (isNew) {
      fs.mkdirSync(path.dirname(specPath), { recursive: true });

      edit.createFile(specUri, {
        ignoreIfExists: true,
        contents: Buffer.from(finalContent),
      });
      await vscode.workspace.applyEdit(edit);

      const doc = await vscode.workspace.openTextDocument(specUri);
      await doc.save();

      log(`Created: ${path.basename(specPath)} — SS-GENERATED block written, SS-USER-TESTS section ready`);

      const shouldOpen = vscode.workspace
        .getConfiguration('silentspec')
        .get<boolean>('openSpecOnCreate', true);

      if (shouldOpen) {
        await vscode.window.showTextDocument(doc, {
          viewColumn: vscode.ViewColumn.Beside,
          preserveFocus: true,
        });
      }

    } else {
      const doc = await vscode.workspace.openTextDocument(specUri);
      const fullRange = new vscode.Range(
        doc.positionAt(0),
        doc.positionAt(doc.getText().length)
      );
      edit.replace(specUri, fullRange, finalContent);
      await vscode.workspace.applyEdit(edit);
      await doc.save();

      log(`Updated: ${path.basename(specPath)} — SS-GENERATED block regenerated, SS-USER-TESTS preserved`);
    }

  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);
    log(`Error: file writer failed for ${path.basename(specPath)} — ${msg}`);
  }
}