import * as vscode from 'vscode';
import { analyzeFile } from './astAnalyzer';
import { extractContext, SilentSpecContext } from './contextExtractor';
import { resolveSpecPathWithInfo } from './fileWriter';
import {
  SSMarker,
  readMarker,
  reconcile,
  computeWorkList,
  updateMarkerOnly,
  rebuildMarkerFromContent,
  DEFAULT_MAX_FUNCTIONS_PER_RUN,
} from './utils/markerManager';


export async function runGapFinder(
  log: (msg: string) => void,
  onPromptReady: (
    ctx: SilentSpecContext,
    filePath: string,
    log: (msg: string) => void,
    abortSignal: AbortSignal,
    exportedFunctions: string[],
    exportTypes: Record<string, 'default' | 'named'>
  ) => Promise<void>,
  filePathOverride?: string
): Promise<void> {
  let filePath: string;

  if (filePathOverride) {
    filePath = filePathOverride;
  } else {
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
      vscode.window.showWarningMessage('SilentSpec: No active file open');
      return;
    }
    filePath = editor.document.uri.fsPath;
    if (/\.(test|spec)\.[tj]sx?$/.test(filePath)) {
      vscode.window.showWarningMessage('SilentSpec: Cannot run Gap Finder on a test file');
      return;
    }
  }

  await vscode.window.withProgress({
    location: vscode.ProgressLocation.Window,
    title: '$(sync~spin) SS: Finding test gaps...',
  }, async () => {
    log(`Gap Finder: analyzing ${filePath}`);

    const result = analyzeFile(filePath, log);
    if (!result.isTestable) {
      vscode.window.showInformationMessage(
        `SilentSpec: No testable functions — ${result.skipReason}`
      );
      return;
    }

    log(`Gap Finder: ${result.exportedFunctions.length} function(s) detected`);

    // Read marker from existing spec
    const resolution = await resolveSpecPathWithInfo(filePath, log);
    const specPath = resolution.specPath;
    let existingMarker: SSMarker | null = null;

    if (resolution.reason === 'new-sister-for-unmanaged' && !resolution.companionPath) {
      vscode.window.showWarningMessage('SilentSpec: Save the source file first to create the managed spec.');
      log('Gap Finder: unmanaged spec found but no companion path was available — skipping');
      return;
    }

    if (resolution.reason === 'new-sister-for-unmanaged' && resolution.companionPath) {
      vscode.window.showWarningMessage('SilentSpec: Save the source file first to create the managed SilentSpec companion file.');
      log(`Gap Finder: unmanaged spec found at ${resolution.companionPath} — save source first to create ${specPath}`);
      return;
    }

    if (resolution.reason === 'existing-managed-sister') {
      log(`Gap Finder: using managed sister file ${specPath}`);
    }

    try {
      const bytes = await vscode.workspace.fs.readFile(vscode.Uri.file(specPath));
      const specContent = Buffer.from(bytes).toString('utf8');
      const { marker } = readMarker(specContent);
      const rebuiltMarker = rebuildMarkerFromContent(specContent, result.exportedFunctions);
      existingMarker = rebuiltMarker ?? marker;
      if (marker) {
        log(`Gap Finder: marker read — covered: [${marker.covered.join(', ')}] pending: [${marker.pending.join(', ')}]`);
        if (rebuiltMarker && rebuiltMarker.covered.join(',') !== marker.covered.join(',')) {
          log(`Gap Finder: marker reconciled from generated content — covered: [${rebuiltMarker.covered.join(', ')}] pending: [${rebuiltMarker.pending.join(', ')}]`);
          const patched = updateMarkerOnly(specContent, rebuiltMarker);
          await vscode.workspace.fs.writeFile(
            vscode.Uri.file(specPath),
            Buffer.from(patched, 'utf8')
          );
        }
      } else {
        // Spec file exists but has no SS marker — check if managed by SilentSpec
        const hasSilentSpecHeader = specContent.includes('// @auto-generated by SilentSpec');
        const hasAnySSMarker =
          specContent.includes('// <SS-IMPORTS-START>') || specContent.includes('// <SS-IMPORTS-END>') ||
          specContent.includes('// <SS-HELPERS-START>') || specContent.includes('// <SS-HELPERS-END>') ||
          specContent.includes('// <SS-USER-TESTS>')    || specContent.includes('// </SS-USER-TESTS>') ||
          specContent.includes('// <SS-GENERATED-START') || specContent.includes('// <SS-GENERATED-END>');
        if (!hasSilentSpecHeader && !hasAnySSMarker) {
          vscode.window.showWarningMessage('SilentSpec: This file is not managed by SilentSpec');
          log('Gap Finder: spec file not managed by SilentSpec — skipping');
          return;
        }
        log('Gap Finder: no marker found — treating all functions as gaps');
      }
    } catch {
      log('Gap Finder: no spec found — full generation');
    }

    // Reconcile marker against current exports and compute work list
    const reconciled = reconcile(existingMarker, result.exportedFunctions);

    if (reconciled.dropped.length > 0) {
      log(`Gap Finder: dropped stale entries — [${reconciled.dropped.join(', ')}]`);
    }

    const maxPerRun = vscode.workspace
      .getConfiguration('silentspec')
      .get<number>('maxFunctionsPerRun', DEFAULT_MAX_FUNCTIONS_PER_RUN);

    const workList = computeWorkList(reconciled, maxPerRun);

    if (workList.length === 0) {
      vscode.window.showInformationMessage('SilentSpec: All functions covered ✓');
      log('Gap Finder: all functions covered — nothing to generate');
      return;
    }

    const pendingCount = reconciled.pending.filter(fn => workList.includes(fn)).length;
    const newCount     = workList.length - pendingCount;
    log(`Gap Finder: work list — [${workList.join(', ')}] (${pendingCount} resuming, ${newCount} new)`);

    if (pendingCount > 0) {
      vscode.window.showInformationMessage(
        `SilentSpec: Resuming ${pendingCount} pending + ${newCount} new functions...`
      );
    } else {
      const display = workList.length <= 3 ? workList.join(', ') : `${workList.length} functions`;
      vscode.window.showInformationMessage(`SilentSpec: Generating tests for ${display}...`);
    }

    // Build ctx with the work list — the extension.ts findGaps callback ignores
    // this ctx and calls runOneGapBatch directly (which builds its own prompt),
    // but we pass a valid ctx to satisfy the interface contract.
    const gapCtx = extractContext(filePath, result.exportedFunctions, result.imports, log, result.exportTypes);
    gapCtx.specPath = specPath;
    gapCtx.workList = workList;
    gapCtx.internalTypes = result.internalTypes;

    const controller = new AbortController();
    await onPromptReady(
      gapCtx,
      filePath,
      log,
      controller.signal,
      result.exportedFunctions,
      result.exportTypes
    );
  });
}
